leftnav:
- identifier: external--1180594484-1684528534515
  name: About Terrascope
  url: https://terrascope.mit.edu/overview/
  weight: 10
- identifier: external-1611017699-1684528590488
  name: Past Years' Topics
  url: https://terrascope.mit.edu/past-years-topics/
  weight: 20
- identifier: external-1618981470-1684528632468
  name: Terrascope Radio
  url: https://terrascope.mit.edu/radio/
  weight: 30
